stages:
  - build
  - test
  - upload
  - release

variables:
  GOTOOLCHAIN: local

zfs-auto-snapshot:
  stage: build
  needs: []
  tags:
    - FreeBSD
  script:
    - export GOFLAGS="-trimpath"
    - export GOPROXY=https://athens.mouf.io
    - export GO_LDFLAGS="-s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o zfs-auto-snapshot ./cmd/zfs-auto-snapshot

zfs-cleanup-snapshots:
  stage: build
  needs: []
  tags:
    - FreeBSD
  script:
    - export GOFLAGS="-trimpath"
    - export GOPROXY=https://athens.mouf.io
    - export GO_LDFLAGS="-s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o zfs-cleanup-snapshots ./cmd/zfs-cleanup-snapshots

zfs-snapshot-mysql:
  stage: build
  needs: []
  tags:
    - FreeBSD
  script:
    - export GOFLAGS="-trimpath"
    - export GOPROXY=https://athens.mouf.io
    - export GO_LDFLAGS="-s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o zfs-snapshot-mysql ./cmd/zfs-snapshot-mysql

lint:
  stage: test
  needs: []
  tags:
    - FreeBSD
  script:
    - go fmt $(go list ./...) | diff -u /dev/null -
    - go vet $(go list ./...)
    - export GOBIN=${HOME}/bin
    - export PATH=${GOBIN}:${PATH}
    - go mod tidy -v
    - git diff | diff -u /dev/null -
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.7
    - golangci-lint run ./...
