name: Build and Release Go Binary
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
env:
  GOGC: 50
  CGO_ENABLED: 0
permissions:
  contents: write # needed for creating releases
jobs:
  build:
    runs-on: arc-runner-set-zfstools
    strategy:
      matrix:
        os: ['freebsd', 'linux']
        arch: ['amd64', 'arm64']
        binary: ['zfs-auto-snapshot', 'zfs-cleanup-snapshots', 'zfs-snapshot-mysql']
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get all tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          go get ./...
      - name: Determine build variables
        id: vars
        run: |
          VERSION=${GITHUB_REF_NAME}
          if [[ "$VERSION" == "" ]]; then
            VERSION="dev"
          fi
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          export GOFLAGS="-trimpath"
          mkdir -p ${{ matrix.arch }}-${{ matrix.os }}
          go build -v -ldflags "-s -w -extldflags -static \
            -X 'main.Version=${{ steps.vars.outputs.version }}' \
            -X 'main.Commit=${{ steps.vars.outputs.commit }}' \
            -buildid=${{ steps.vars.outputs.version }}.${{ steps.vars.outputs.commit }} \
          " -o ${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.binary }} ./cmd/${{ matrix.binary }}
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.binary }}
          path: |
            ${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.binary }}
  release:
    runs-on: arc-runner-set-zfstools
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download amd64-freebsd-zfs-auto-snapshot
        uses: actions/download-artifact@v4
        with:
          name: binary-amd64-freebsd-zfs-auto-snapshot
          path: artifacts/amd64-freebsd
      - name: Download amd64-freebsd-zfs-cleanup-snapshots
        uses: actions/download-artifact@v4
        with:
          name: binary-amd64-freebsd-zfs-cleanup-snapshots
          path: artifacts/amd64-freebsd
      - name: Download amd64-freebsd-zfs-snapshot-mysql
        uses: actions/download-artifact@v4
        with:
          name: binary-amd64-freebsd-zfs-snapshot-mysql
          path: artifacts/amd64-freebsd
      - name: Download arm64-freebsd-zfs-auto-snapshot
        uses: actions/download-artifact@v4
        with:
          name: binary-arm64-freebsd-zfs-auto-snapshot
          path: artifacts/arm64-freebsd
      - name: Download arm64-freebsd-zfs-cleanup-snapshots
        uses: actions/download-artifact@v4
        with:
          name: binary-arm64-freebsd-zfs-cleanup-snapshots
          path: artifacts/arm64-freebsd
      - name: Download arm64-freebsd-zfs-snapshot-mysql
        uses: actions/download-artifact@v4
        with:
          name: binary-arm64-freebsd-zfs-snapshot-mysql
          path: artifacts/arm64-freebsd
      - name: Download amd64-linux-zfs-auto-snapshot
        uses: actions/download-artifact@v4
        with:
          name: binary-amd64-linux-zfs-auto-snapshot
          path: artifacts/amd64-linux
      - name: Download amd64-linux-zfs-cleanup-snapshots
        uses: actions/download-artifact@v4
        with:
          name: binary-amd64-linux-zfs-cleanup-snapshots
          path: artifacts/amd64-linux
      - name: Download amd64-linux-zfs-snapshot-mysql
        uses: actions/download-artifact@v4
        with:
          name: binary-amd64-linux-zfs-snapshot-mysql
          path: artifacts/amd64-linux
      - name: Download arm64-linux-zfs-auto-snapshot
        uses: actions/download-artifact@v4
        with:
          name: binary-arm64-linux-zfs-auto-snapshot
          path: artifacts/arm64-linux
      - name: Download arm64-linux-zfs-cleanup-snapshots
        uses: actions/download-artifact@v4
        with:
          name: binary-arm64-linux-zfs-cleanup-snapshots
          path: artifacts/arm64-linux
      - name: Download arm64-linux-zfs-snapshot-mysql
        uses: actions/download-artifact@v4
        with:
          name: binary-arm64-linux-zfs-snapshot-mysql
          path: artifacts/arm64-linux
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: rename zfs-auto-snapshot for amd64-freebsd
        run: mv artifacts/amd64-freebsd/amd64-freebsd-zfs-auto-snapshot artifacts/amd64-freebsd/zfs-auto-snapshot
      - name: rename zfs-cleanup-snapshots for amd64-freebsd
        run: mv artifacts/amd64-freebsd/amd64-freebsd-zfs-cleanup-snapshots artifacts/amd64-freebsd/zfs-cleanup-snapshots
      - name: rename zfs-snapshot-mysql for amd64-freebsd
        run: mv artifacts/amd64-freebsd/amd64-freebsd-zfs-snapshot-mysql artifacts/amd64-freebsd/zfs-snapshot-mysql
      - name: rename zfs-auto-snapshot for arm64-freebsd
        run: mv artifacts/arm64-freebsd/arm64-freebsd-zfs-auto-snapshot artifacts/arm64-freebsd/zfs-auto-snapshot
      - name: rename zfs-cleanup-snapshots for arm64-freebsd
        run: mv artifacts/arm64-freebsd/arm64-freebsd-zfs-cleanup-snapshots artifacts/arm64-freebsd/zfs-cleanup-snapshots
      - name: rename zfs-snapshot-mysql for arm64-freebsd
        run: mv artifacts/arm64-freebsd/arm64-freebsd-zfs-snapshot-mysql artifacts/arm64-freebsd/zfs-snapshot-mysql
      - name: rename zfs-auto-snapshot for amd64-linux
        run: mv artifacts/amd64-linux/amd64-linux-zfs-auto-snapshot artifacts/amd64-linux/zfs-auto-snapshot
      - name: rename zfs-cleanup-snapshots for amd64-linux
        run: mv artifacts/amd64-linux/amd64-linux-zfs-cleanup-snapshots artifacts/amd64-linux/zfs-cleanup-snapshots
      - name: rename zfs-snapshot-mysql for amd64-linux
        run: mv artifacts/amd64-linux/amd64-linux-zfs-snapshot-mysql artifacts/amd64-linux/zfs-snapshot-mysql
      - name: rename zfs-auto-snapshot for arm64-linux
        run: mv artifacts/arm64-linux/arm64-linux-zfs-auto-snapshot artifacts/arm64-linux/zfs-auto-snapshot
      - name: rename zfs-cleanup-snapshots for arm64-linux
        run: mv artifacts/arm64-linux/arm64-linux-zfs-cleanup-snapshots artifacts/arm64-linux/zfs-cleanup-snapshots
      - name: rename zfs-snapshot-mysql for arm64-linux
        run: mv artifacts/arm64-linux/arm64-linux-zfs-snapshot-mysql artifacts/arm64-linux/zfs-snapshot-mysql
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: tar amd64-FreeBSD
        run: tar -czf ../../zfstools-go-${{ github.ref_name }}-amd64-freebsd.tar.gz zfs-auto-snapshot zfs-cleanup-snapshots zfs-snapshot-mysql
        working-directory: artifacts/amd64-freebsd
      - name: tar arm64-FreeBSD
        run: tar -czf ../../zfstools-go-${{ github.ref_name }}-arm64-freebsd.tar.gz zfs-auto-snapshot zfs-cleanup-snapshots zfs-snapshot-mysql
        working-directory: artifacts/arm64-freebsd
      - name: tar amd64-Linux
        run: tar -czf ../../zfstools-go-${{ github.ref_name }}-amd64-linux.tar.gz zfs-auto-snapshot zfs-cleanup-snapshots zfs-snapshot-mysql
        working-directory: artifacts/amd64-linux
      - name: tar arm64-Linux
        run: tar -czf ../../zfstools-go-${{ github.ref_name }}-arm64-linux.tar.gz zfs-auto-snapshot zfs-cleanup-snapshots zfs-snapshot-mysql
        working-directory: artifacts/arm64-linux
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: artifacts/*.tar.bz2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
