name: Build and Release Go Binary
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
env:
  GOGC: 50
  CGO_ENABLED: 0
permissions:
  contents: write # needed for creating releases
jobs:
  build:
    runs-on: arc-runner-set-zfstools
    strategy:
      matrix:
        os: ['freebsd', 'linux']
        arch: ['amd64', 'arm64']
    steps:
      - name: Checkout source
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # get all tags
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          go get ./...
      - name: Determine build variables
        id: vars
        run: |
          VERSION=${GITHUB_REF_NAME}
          if [[ "$VERSION" == "" ]]; then
            VERSION="dev"
          fi
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          export GOFLAGS="-trimpath"
          go build -v -ldflags "-s -w -extldflags -static \
            -X 'main.Version=${{ steps.vars.outputs.version }}' \
            -X 'main.Commit=${{ steps.vars.outputs.commit }}' \
            -buildid=${{ steps.vars.outputs.version }}.${{ steps.vars.outputs.commit }} \
          " -o zfs-auto-snapshot ./cmd/zfs-auto-snapshot
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.arch }}-${{ matrix.os }}
          path: |
            zfs-auto-snapshot
  release:
    runs-on: arc-runner-set-zfstools
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v8
        with:
          pattern: binary-*
          path: artifacts
      - name: Create hard links and archives
        run: |
          for platform in amd64-freebsd arm64-freebsd amd64-linux arm64-linux; do
            dir="artifacts/binary-${platform}"
            chmod 0755 "${dir}/zfs-auto-snapshot"
            ln "${dir}/zfs-auto-snapshot" "${dir}/zfs-cleanup-snapshots"
            ln "${dir}/zfs-auto-snapshot" "${dir}/zfs-snapshot-mysql"
            tar -C "${dir}" -czvf "artifacts/zfstools-go-${{ github.ref_name }}-${platform}.tar.gz" \
              zfs-auto-snapshot zfs-cleanup-snapshots zfs-snapshot-mysql
          done
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
